language: python

matrix:
    include:
        - python: 2.7
          os: linux
          env: BUILD_COMMAND=sdist

        - python: 3.6
          os: linux
          env: BUILD_COMMAND=sdist

        - language: generic
          os: osx
          env: 
              - BUILD_COMMAND=bdist_wheel
              - PYTHON_VERSION=2

        - language: generic
          os: osx
          env: 
              - BUILD_COMMAND=bdist_wheel
              - PYTHON_VERSION=3
                
cache:
    apt: true

before_install:
    # On MacOS: install python3 if needed
    - source ./ci/travis_osx.sh

install:

    # Upgrade distribution modules

    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools

    # Install build dependencies
    - pip install --upgrade wheel
    - pip install --upgrade numpy

    # Print Python info
    - python ./ci/info_platform.py
    - pip list

    # Generate source package or wheel
    - python setup.py $BUILD_COMMAND
    - ls dist

script:
    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - pip install --upgrade pip

    # Dependencies
    - pip install matplotlib
    - pip install fisx
    - pip install h5py
    - pip install silx

    # Install from source package
    - pip install --pre --find-links dist/ --no-cache-dir --no-index PyMca5 $PIP_INSTALL_EXTRA_ARGS

    # Print Python info
    - python ci/info_platform.py
    - pip list

    # Run the tests
    - cd ..
    - python -m PyMca5.tests.TestAll
