dist: xenial

language: python

matrix:
    include:
        - python: 2.7
          os: linux
          env:
              - BUILD_COMMAND=sdist
              - QT_BINDING=PySide2

        - python: 3.6
          os: linux
          env:
              - BUILD_COMMAND=sdist
              - QT_BINDING=PyQt5

        # No particular need to test Python 2 on OSX
        #- language: generic
        #  os: osx
        #  env: 
        #      - BUILD_COMMAND=bdist_wheel
        #      - PYTHON_VERSION=2
        #      - QT_BINDING=PySide2

        - language: generic
          os: osx
          env: 
              - BUILD_COMMAND=bdist_wheel
              - PYTHON_VERSION=3
              - QT_BINDING=PyQt5

cache:
    apt: true

addons:
    apt:
        packages:
            - libgl1-mesa-dev  # For OpenGL
            - libegl1-mesa  # Required by Qt xcb platform plugin
            - libxkbcommon-x11-0  # needed for Qt plugins
            - libxkbcommon0  # needed for Qt plugins
            - libxkbcommon-dev  # needed for Qt plugins

services:
    - xvfb

before_install:
    # On MacOS: install python3 if needed
    - source ./ci/travis_osx.sh

    # X server
    - if [ "$TRAVIS_OS_NAME" == "linux" ];
      then
          export DISPLAY=:99.0;
      fi

install:
    # Upgrade distribution modules
    - python -m pip install --upgrade pip
    - pip install --upgrade setuptools

    # Install build dependencies
    - pip install --upgrade wheel
    - pip install --upgrade numpy

    # Print Python info
    - python ./ci/info_platform.py
    - pip list

    # Generate source package or wheel
    - python setup.py $BUILD_COMMAND
    - ls dist

script:
    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - pip install --upgrade pip

    # Dependencies
    - pip install matplotlib
    - pip install fisx
    - pip install h5py
    - pip install silx --pre --find-links https://silx.gitlab-pages.esrf.fr/bob/silx/
    - if [[ ! -z $QT_BINDING ]];
      then
          pip install $QT_BINDING;
      fi

    # Install from source package
    - pip install --pre --find-links dist/ --no-cache-dir --no-index PyMca5 $PIP_INSTALL_EXTRA_ARGS

    # Print Python info
    - python ci/info_platform.py
    - pip list

    # Run the tests
    - cd ..
    - python -m PyMca5.tests.TestAll
