#!python

import os
import sys
import PyMca5.PyMcaGui.pymca as target

fname = os.path.join(os.path.dirname(target.__file__), 'Mca2Edf.py')
f = open(fname, "rb")
code_txt = f.read()
f.close()
if sys.version_info < (3, 6):
    code = compile(code_txt, fname, 'exec')
else:
    code = code_txt
exec(code)
