# This is a basic workflow to help you get started with Actions

name: MacOs (app and dmg)

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:

env:
  PROJECT: Pymca_release_test
  PROJECT_LOWER: pymca_release_test
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# Fat binaries

  macos11_pyinstaller_python312:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ "3.12" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set environment for 10.9 compatibility
        run: |
          echo "MACOSX_DEPLOYMENT_TARGET=10.9" >> $GITHUB_ENV
          echo "CFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV
          echo "LDFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install "setuptools<81"
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/numpy-1.26.2-cp312-cp312-macosx_10_9_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/h5py-3.10.0-cp312-cp312-macosx_11_0_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/psutil-5.9.6-cp312-abi3-macosx_10_9_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/Pillow-10.1.0-cp312-cp312-macosx_11_0_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/tornado-6.3.3-cp38-abi3-macosx_10_9_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/contourpy-1.2.0-cp312-cp312-macosx_11_0_universal2.whl
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/kiwisolver-1.4.5-cp312-cp312-macosx_11_0_universal2.whl
          pip install cycler==0.12.1
          pip install fonttools==4.45.1
          pip install packaging==23.2
          pip install pyparsing==3.1.1
          pip install python_dateutil==2.8.2
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/matplotlib-3.8.2-cp312-cp312-macosx_11_0_universal2.whl
          pip install h5py
          pip install hdf5plugin
          pip install PySide6==6.6.0
          pip install lxml==4.9.3
          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/fabio-2023.10.0-cp312-cp312-macosx_10_9_universal2.whl
          pip install fisx
          pip install git+https://github.com/silx-kit/silx.git
          pip install PyOpenGL
          pip install qtconsole==5.5.1
          pip install PyInstaller==6.2.0
          pip install Cython
          pip install wheel
          pip install --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test
          pip install git+https://github.com/vasole/bcflight.git

      - name: Build with PyInstaller (universal2)
        run: |
          python build-pyinstaller.py universal2
          ls dist
          find dist/ -type f -perm +111 | while read -r file; do
            version=$(otool -l "$file" 2>/dev/null | awk '/LC_VERSION_MIN_MACOSX/ {show=1} show && /version / {print $2; show=0}' | head -n 1)
            if [ -n "$version" ]; then
              echo "$version  <-  $file"
            fi
          done | sort

      ### correct and test app file

      - name: Move .app to /Applications
        run: |
          sudo mv ./dist/PyMca5.9.4.app /Applications/
          ls -l /Applications/PyMca5.9.4.app/Contents/MacOS

      - name: Make main binary executable
        run: chmod +x /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain

      - name: Rename __dot__dylibs folders to .dylibs
        run: |
          find /Applications/PyMca5.9.4.app -depth -type d -name '__dot__dylibs' | while IFS= read -r dir; do
            parent_dir=$(dirname "$dir")
            target="$parent_dir/.dylibs"

            if [ -e "$target" ]; then
              echo "⚠️ Skipping: $target already exists."
            else
              mv "$dir" "$target"
              if [ -d "$target" ]; then
                if [ "$(ls -A "$target")" ]; then
                  echo "✅ Renamed and verified: $dir → $target (not empty)"
                else
                  echo "⚠️ Renamed: $dir → $target but it's empty"
                fi
              else
                echo "❌ Rename failed: $dir → $target does not exist"
              fi
            fi
          done

      - name: Run the app to check it launches
        run: |
          set -e

          echo "Launching PyMcaMain..."

          # Start the app in the background
          /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain &
          APP_PID=$!

          echo "App started with PID $APP_PID"

          # Wait up to 120 seconds for it to crash or hang
          for i in {1..120}; do
            if ! ps -p $APP_PID > /dev/null; then
              echo "App exited early. Checking exit code..."
              wait $APP_PID
              EXIT_CODE=$?
              if [ $EXIT_CODE -ne 0 ]; then
                echo "App exited with error code $EXIT_CODE"
                exit $EXIT_CODE
              else
                echo "App exited cleanly before 2 minutes."
                exit 1
              fi
            fi
            sleep 1
          done

          echo "App ran for 2 minutes without crashing. Killing it now..."
          kill $APP_PID || true
          wait $APP_PID || true
          echo "App test complete."

      - name: Copy .app out /Applications
        run: |
          sudo mkdir -p myappfolder
          sudo cp -R "/Applications/PyMca5.9.4.app" myappfolder/

      - name: Cleanup
        run: |
          sudo rm -rf /Applications/PyMca5.9.4.app

      ### dmg test

      - name: Mount the DMG
        run: |
          hdiutil attach dist/PyMca5.9.4.dmg -mountpoint /Volumes/PyMcaApp

      - name: Copy .app to /Applications
        run: |
          sudo cp -R "/Volumes/PyMcaApp/PyMca5.9.4.app" /Applications/

      - name: Make main binary executable
        run: chmod +x /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain

      - name: Run the app to check it launches
        run: |
          set -e

          echo "Launching PyMcaMain..."

          # Start the app in the background
          /Applications/PyMca5.9.4.app/Contents/MacOS/PyMcaMain &
          APP_PID=$!

          echo "App started with PID $APP_PID"

          # Wait up to 120 seconds for it to crash or hang
          for i in {1..120}; do
            if ! ps -p $APP_PID > /dev/null; then
              echo "App exited early. Checking exit code..."
              wait $APP_PID
              EXIT_CODE=$?
              if [ $EXIT_CODE -ne 0 ]; then
                echo "App exited with error code $EXIT_CODE"
                exit $EXIT_CODE
              else
                echo "App exited cleanly before 2 minutes."
                exit 0
              fi
            fi
            sleep 1
          done

          echo "App ran for 5 minutes without crashing. Killing it now..."
          kill $APP_PID || true
          wait $APP_PID || true
          echo "App test complete."

      - name: Cleanup
        run: |
          sudo rm -rf /Applications/PyMca5.9.4.app

      # upload .dmg
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-pyinstaller-artifacts-dmg
          path: dist/*.dmg
          retention-days: 1

#      # also upload to release
#      - name: Upload dmg to GitHub Release
#        if: github.event_name == 'release'
#        uses: softprops/action-gh-release@v1
#        with:
#          files: dist/*.dmg
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # upload .app as well
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-pyinstaller-artifacts-dashdotfix
          path: myappfolder/*
          include-hidden-files: true
          retention-days: 1